# Generated by Django 5.2.1 on 2025-05-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_header', models.ImageField(default='/banner1.png', upload_to='banners', verbose_name='图片')),
                ('img_detail_header', models.ImageField(default='/banner1.png', upload_to='banners', verbose_name='介绍内容标题图片')),
                ('img_detail_detail', models.ImageField(default='/banner1.png', upload_to='banners', verbose_name='介绍内容图片')),
                ('name', models.CharField(max_length=32, verbose_name='介绍标题')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '介绍表',
            },
        ),
    ]
