# Generated by Django 5.2.1 on 2025-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_company_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_detail',
            name='img_detail_detail',
            field=models.ImageField(default='/banner1.png', upload_to='company_datail', verbose_name='介绍内容图片'),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='img_detail_header',
            field=models.ImageField(default='/banner1.png', upload_to='company_datail', verbose_name='介绍内容标题图片'),
        ),
        migrations.AlterField(
            model_name='company_detail',
            name='img_header',
            field=models.ImageField(default='/banner1.png', upload_to='company_datail', verbose_name='标题图片'),
        ),
    ]
