# Generated by Django 5.2.1 on 2025-05-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_alter_company_detail_img_detail_detail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='igm',
            new_name='img',
        ),
    ]
